# Case Geometry
# All dimensions in meters
domain:
  width: 6.0
  height: 2.0

# Obstacle Definition (Rectangle attached to the bottom wall)
obstacle:
  # x-coordinates for the left and right edges of the obstacle
  x_min: 2.0
  x_max: 3.0
  # y-coordinate for the top edge of the obstacle
  height: 1.0

# Fluid and Flow Properties
inlet_velocity: [1.5, 0, 0] # [Ux, Uy, Uz]
kinematic_viscosity: 0.01 # nu [m^2/s]

# Mesh Grading
# Number of cells in each direction for each block
# This needs to be carefully tuned with the geometry
grading:
  h1_cells: 20 # Cells before obstacle
  h2_cells: 10 # Cells along obstacle
  h3_cells: 30 # Cells after obstacle
  v1_cells: 20 # Cells below obstacle top / in main channel